name: Fall 24 - Export Pluto notebooks & Deploy
on:
    push:
        branches:
            - Fall24
    workflow_dispatch:
concurrency:
    group: export
    cancel-in-progress: true

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Fall 24 source
              uses: actions/checkout@v4

            - name: 🙌 Install Julia
              uses: julia-actions/setup-julia@v2
              with:
                  version: "1.10.4"

            - name: ⏱ Cache notebook states
              uses: actions/cache@v4
              with:
                path: _cache
                key: ${{ runner.os }}-pluto_state_cache-v3-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}-${{ github.run_id }}
                restore-keys: |
                    ${{ runner.os }}-pluto_state_cache-v3-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}

            - name: ⏱ Cache .julia
              uses: actions/cache@v4
              with:
                path: ~/.julia
                key: ${{ runner.os }}-dotjulia-v1-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}-${{ github.run_id }}
                restore-keys: |
                    ${{ runner.os }}-dotjulia-v1-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}

            - name: 📅 Checkout Fall20, Spring21, Fall22, Fall23 output
              uses: actions/checkout@v4
              with:
                  path: Fall23-output
                  ref: Fall23-output

            - name: 🪴 Generate site
              run: julia --project=pluto-deployment-environment -e '
                  import Pkg;
                  Pkg.instantiate();

                  include("./generate.jl")'

            
            - name: 📰 Upload site generation report
              uses: actions/upload-artifact@v4
              if: always()
              with:
                path: generation_report.html

            - name: 🔀 Combine semesters into single site
              run: |
                mkdir www
                mv Fall23-output/Fall20/ www/Fall20
                mv Fall23-output/Spring21/ www/Spring21
                mv Fall23-output/Fall22/ www/Fall22
                mv Fall23-output/Fall23/ www/Fall23
                mv _site www/Fall24
                mv extra_outputs/* www

            - name: 🚀 Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: Fall24-output
                  folder: www
